from enum import Enum
from typing import Optional, Dict, Any
import datetime


class AssetEventType(str, Enum):
    ASSET_DISCOVERED = "ASSET_DISCOVERED"
    ASSET_UPDATED = "ASSET_UPDATED"
    ASSET_REMOVED = "ASSET_REMOVED"
    DOMAIN_DISCOVERED = "DOMAIN_DISCOVERED"
    SUBDOMAIN_DISCOVERED = "SUBDOMAIN_DISCOVERED"
    ENDPOINT_DISCOVERED = "ENDPOINT_DISCOVERED"
    PAGE_CRAWLED = "PAGE_CRAWLED"
    FORM_DISCOVERED = "FORM_DISCOVERED"
    PARAMETER_DISCOVERED = "PARAMETER_DISCOVERED"
    JAVASCRIPT_DISCOVERED = "JAVASCRIPT_DISCOVERED"
    TECHNOLOGY_IDENTIFIED = "TECHNOLOGY_IDENTIFIED"
    GRAPH_NODE_ADDED = "GRAPH_NODE_ADDED"
    GRAPH_EDGE_ADDED = "GRAPH_EDGE_ADDED"
    ASSET_ANALYSIS_STARTED = "ASSET_ANALYSIS_STARTED"
    ASSET_ANALYSIS_COMPLETED = "ASSET_ANALYSIS_COMPLETED"
    ASSET_ANALYSIS_FAILED = "ASSET_ANALYSIS_FAILED"
